SELECT ITP.ITMREFBPS_0,ITM.ITMDES1_0,YFA2.YFA_LIB_0, ITM.EANCOD_0,SUM(STO.QTYSTU_0 - ITV.SALSTO_0) 
FROM  ITMFACILIT ITF
LEFT JOIN ITMMASTER ITM ON ITM.ITMREF_0 = ITF.ITMREF_0
LEFT JOIN ITMBPS ITP ON ITP.ITMREF_0 = ITF.ITMREF_0 AND ITP.PIO_0 = 0
JOIN STOCK STO ON ITF.ITMREF_0 = STO.ITMREF_0 AND STO.STOFCY_0 = (%1%) AND LOC_0 in ('A2A','B1A') AND STA_0 <> 'R'
LEFT JOIN   ITMMVT ITV ON ITV.ITMREF_0 = ITF.ITMREF_0 AND ITV.STOFCY_0 in (%1%)
LEFT JOIN   BPSUPPLIER BPS ON BPS.BPSNUM_0 = ITP.BPSNUM_0
LEFT JOIN   YFAMART YFA0 ON ITM.YITM_FAM2_0 = YFA0.YFA_CODE_0 AND YFA0.YNF_NIV_0 = 1 AND YFA0.YNF_REG_0 = 2
LEFT JOIN   YFAMART YFA1 ON ITM.YITM_FAM2_1 = YFA1.YFA_CODE_0 AND YFA1.YNF_NIV_0 = 2 AND YFA1.YNF_REG_0 = 2
LEFT JOIN   YFAMART YFA2 ON ITM.YITM_FAM2_2 = YFA2.YFA_CODE_0 AND YFA2.YNF_NIV_0 = 3 AND YFA2.YNF_REG_0 = 2
LEFT JOIN   YFAMART YFA3 ON ITM.YITM_FAM2_3 = YFA3.YFA_CODE_0 AND YFA3.YNF_NIV_0 = 4 AND YFA3.YNF_REG_0 = 2
WHERE ITF.STOFCY_0 in (%1%) AND (STO.QTYSTU_0 - ITV.SALSTO_0) <> 0
GROUP BY ITP.ITMREFBPS_0,ITM.YITM_ANRAV_0,ITM.ITMDES1_0,YFA2.YFA_LIB_0, ITM.EANCOD_0
